# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Expose the port that the Angular development server will use (default is 4200)
EXPOSE 4200

# Set the default command to run the ng serve command
CMD ["npm", "run", "start"]
